### ISSUE TITLE
Parent. scope broken

### ISSUE THREAD

**Issue by Nashorn** [davidvaccaro/kruntch.js#1]
It appears that the reference to the .Parent scope from a child (in a for/with loop) is broken. It gives an error "value is undefined". The work-around is to duplicate the relevant parent values in each json-child item.

Is there a fix?

**Comment by davidvaccaro** [comment]
Nashorn,
I'll take a look today  though... If you would like to fix it and submit a pull-request, I'd be happy to review and and merge asap.
Dave

**Comment by davidvaccaro** [comment]
Nashorn,

Can you send me a simple template example that produces the issue?

Thanks,
Dave

**Comment by davidvaccaro** [comment]
Nashorn,

I created an example as you described but it appears to work correctly... Can you email me an example that reproduces the error your seeing?

**Comment by Nashorn** [comment]
Hi David,
we figured it out. when used in an if condition, we had to prefix with "this.".
But when outputting, it's just Parent.<some_property>

**Comment by Nashorn** [comment]
We're dealing with some deeply nested objects, and need to refer back to the root object from within a deeply nested <for> block, but the only way seems to be this:
Parent.Parent.Parent.Parent.<some_property>

I would like to know where in the code I can add a new property called:
.Root

Any idea? Could you send me an email at:
jaysmith024 at gmail

Thanks David.
Jay
